services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: battle-arena-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: battle_arena
      MYSQL_USER: battle_user
      MYSQL_PASSWORD: battle_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: battle-arena-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # 后端 API
  backend:
    build: ./backend
    container_name: battle-arena-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://battle_user:battle_pass@mysql:3306/battle_arena
      - JWT_SECRET=your_jwt_secret_key
      - PORT=3001
      - NODE_ENV=production
      - CORS_ORIGIN=http://106.53.187.98
      - MATCH_COST_DIAMONDS=22
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - redis

  # 前端 Nginx
  frontend:
    build: ./frontend
    container_name: battle-arena-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data: 